# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-02 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('comment', models.CharField(max_length=100)),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RegexEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=200, unique=True)),
                ('flags', models.CharField(default=b'e', max_length=10)),
                ('comment', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name=b'date added')),
                ('disabled', models.BooleanField(default=False)),
                ('regex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='django_bro_tables.Regex')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('comment', models.CharField(max_length=100)),
                ('num_fields', models.SmallIntegerField()),
                ('fields', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TableEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name=b'date added')),
                ('c0', models.CharField(max_length=200)),
                ('c1', models.CharField(blank=True, max_length=200)),
                ('c2', models.CharField(blank=True, max_length=200)),
                ('c3', models.CharField(blank=True, max_length=200)),
                ('c4', models.CharField(blank=True, max_length=200)),
                ('c5', models.CharField(blank=True, max_length=200)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='django_bro_tables.Table')),
            ],
        ),
    ]
